### ISSUE TITLE
Calling better-shell-for-current-dir fails if editing a remote file in sudo-mode

### ISSUE THREAD

**Issue by PhilipDaniels** [killdash9/better-shell#8] opened 2017-02-22 21:55 UTC
* Open a remote file in non-sudo mode, e.g. `/phil@deb2:.profile`
* I am then looking at a buffer whose full filename is `/sshx:phil@deb2:/home/phil/.profile`, as proven by recentf and my frame title.
* Invoke **better-shell-sudo-here**
* This works, and I am now looking at a buffer called `/sudo:root@deb2:/home/phil/.profile`
* Invoke **better-shell-for-current-dir**
* This prints an error message, from TRAMP I think, saying "Host deb2 looks like a remote host. sudo can only use the local host".
* Expected behaviour - I should get a remote sudo shell in the appropriate directory.

**Comment by killdash9** [comment] 2018-02-09 18:49
I was unable to reproduce this exactly, but upgrade to the latest version 1.2 / 20180209.1001, and try this again.  I may have fixed it.

**Comment by killdash9** [comment] 2018-06-25 13:23
@PhilipDaniels Is this still happening?  I will close this ticket if I don't hear back from you.

**Comment by PhilipDaniels** [comment] 2018-06-25 13:29
Sorry, I don't know I no longer use Emacs.

**Comment by killdash9** [comment] 2018-06-25 15:54
Closing this issue

**Closed as completed by killdash9** 2018-06-25 15:54 UTC
